appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: WbfIhnpc4LPZ5dK8AFnGPw/M4ym2EXQmppMXEAT17J2OQFt/kj1tqUcNQSEvScUlOR9yeoM82dsPKT+31u3yya9mSYn2CjLyOt+7n31i/9yQZWfKMpDGU4SG+lPF+tU9/Qn+jGsrZnAV5rtyenTly2oK8zaEQYuCIGC//gAsEr8X93Etrvi8swxGNi++bzX288sHjESJkeZJF8dSOOz0kGt5sBzo3/YkZ/HwF00KyUnIi8euNO5Vd6Qpl8vBEqrwN8MdmwQi8Cwy4VNHUWdqv3FX6OyD1BBJKlADxKMIWHmyNulR59gctC1MKuNjIHPtDi4ycJfNM+MbvVBsbsnLQMgKLpuls8AuWvlDPlRkQugpKCTwsatxOwBdIOnrEjhrLG8xlvkjUt/QrT1kggkhYWPk2RnrA0D+Z3FScXC/QiMN08vfLGBXcLirstvF4ook2D5jW0CCzwK5nnguq3Ri7vSFqixuA6ksIrJ/hBSSgwtGFluFyP0OXU9zJQuUTfXsRWyso+YLXOzO3WRt0fVm7xPurkHUW6AJ7uYECSjD3CKPhOk4+Kj9GE8TqJZsrYfnu2H10AwZEKUIJwTTNK+vbUTBVz1HvZW1XpF+Q0fDzwslNW+F1SFqlSDMC/OYJ8k11XIOPTJmSQ9Oc2XPzJhOKP8mNAXXWUTVMnbI9cW2vxs=}
bot:
  automerge: true
